<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "restaurant_adslfhag"
 *
 * Auto generated by Extension Builder 2020-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Restaurant ADSLFHAG',
    'description' => 'Carte de restaurant',
    'category' => 'plugin',
    'author' => 'Adrien Doyhamboure, Simon Lasbrugnas, Flavien Henry--Szatkowski, Alexandre Gendre',
    'author_email' => 'adrien.doyhamboure@etu.u-bordeaux.fr, simon.lasbrugnas@etu.u-bordeaux.fr, flavien.henry-szatkowski@etu.u-bordeaux.fr, alexandre.gendre@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
